image: Visual Studio 2017

install:
  - ps: Start-FileDownload  https://github.com/JetBrains/kotlin/releases/download/v1.3.72/kotlin-native-windows-1.3.72.zip 
  - 7z kotlin-native-windows-1.3.72.zip

build_script:
  - kotlinc src\BranchGenerator.kt

