image: Visual Studio 2019

install:
  - dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
  - wsl sudo apt-get update
  - wsl sudo apt-get install -y zip
  - wsl sudo apt-get install -y default-jdk-headless
  - curl -s "https://get.sdkman.io" | wsl bash
  - wsl source "/home/appveyor/.sdkman/bin/sdkman-init.sh"
  - wsl bash -c "echo source /home/appveyor/.bashrc >> /home/appveyor/.bash_profile"
  - wsl bash -c "echo source /home/appveyor/.bashrc >> /home/appveyor/.profile"
  - wsl cat /home/appveyor/.sdkman/bin/sdkman-init.sh 
  - ps: wsl bash -c "source /home/appveyor/.sdkman/bin/sdkman-init.sh && sdk install kotlin 1.4.10 &> /dev/null"  
  
environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

build_script:  
  - ps: wsl bash -c "/home/appveyor/.sdkman/candidates/kotlin/1.4.10/bin/kotlinc src/BranchGenerator.kt -d BranchGenerator"

