os:
  - linux
  - osx

language: java
addons:
  apt:
    packages:
      - ant

jdk:
  - oraclejdk9
  - openjdk8
  - openjdk9

dist:
- xenial

env:
- TERM=dumb

before_install:
  - curl -s https://get.sdkman.io | bash
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      .  "/home/travis/.sdkman/bin/sdkman-init.sh"
    else
      . "/Users/travis/.sdkman/bin/sdkman-init.sh"
    fi
  - sdk install kotlin

script:
- kotlinc src/BranchGenerator.kt

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
