os:
  - linux
  - osx

matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux

language: java
addons:
  apt:
    packages:
      - ant

jdk:
  - oraclejdk9
  - openjdk8
  - openjdk9

dist:
- xenial

env:
- TERM=dumb

before_install:
  - curl -s https://get.sdkman.io | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin

script:
- kotlinc src/BranchGenerator.kt

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
