language: java
addons:
  apt:
    packages:
      - ant

jdk:
- openjdk8

dist:
- xenial

env:
- TERM=dumb

before_install:
  - curl -s https://get.sdkman.io | bash
  - sdk install kotlin

script:
- kotlinc src/Branch-Generator.kt

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
